import { Router, Request, Response } from 'express';
import { z } from 'zod';
import { asyncHandler } from '../middleware/errorHandler';
import { prisma } from '../services/database';

export const inviteRoutes = Router();

// Schema for creating invite token
const createInviteSchema = z.object({
  userId: z.string(),
});

// POST /api/invite/create - Create a new one-time-use invite token
inviteRoutes.post('/create', asyncHandler(async (req: Request, res: Response) => {
  const { userId } = createInviteSchema.parse(req.body);

  // Verify user exists
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { id: true, name: true }
  });

  if (!user) {
    return res.status(404).json({
      success: false,
      error: 'User not found',
    });
  }

  // Create new invite token (token is auto-generated by Prisma default)
  const inviteToken = await prisma.inviteToken.create({
    data: {
      creatorId: userId,
    },
  });

  console.log(`Created invite token for ${user.name}: ${inviteToken.token}`);

  res.json({
    success: true,
    token: inviteToken.token,
    inviteUrl: `/invite/${inviteToken.token}`,
  });
}));

// GET /api/invite/:token - Validate an invite token
inviteRoutes.get('/:token', asyncHandler(async (req: Request, res: Response) => {
  const { token } = req.params;

  const inviteToken = await prisma.inviteToken.findUnique({
    where: { token },
    include: {
      creator: {
        select: {
          id: true,
          name: true,
          profilePhotoUrl: true,
        }
      }
    }
  });

  if (!inviteToken) {
    return res.status(404).json({
      success: false,
      valid: false,
      error: 'Invalid invite link',
    });
  }

  // Check if already used
  if (inviteToken.usedById) {
    return res.json({
      success: true,
      valid: false,
      used: true,
      error: 'This invite link has already been used',
      creator: inviteToken.creator,
    });
  }

  // Check if expired
  if (inviteToken.expiresAt && inviteToken.expiresAt < new Date()) {
    return res.json({
      success: true,
      valid: false,
      expired: true,
      error: 'This invite link has expired',
      creator: inviteToken.creator,
    });
  }

  res.json({
    success: true,
    valid: true,
    creator: inviteToken.creator,
    createdAt: inviteToken.createdAt,
  });
}));
